# https://taskfile.dev

version: "3"

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org,direct

tasks:
  dev:
    desc: Setup git hooks
    cmds:
      - cp -f scripts/pre-commit.sh .git/hooks/pre-commit

  setup:
    desc: Install dependencies
    cmds:
      - go mod tidy

  build:
    desc: Build the binary
    sources:
      - ./**/*.go
    generates:
      - ./dottie
    cmds:
      - go build -o dottie ./cmd/

  test:
    desc: Run tests
    env:
      LC_ALL: C
    vars:
      TEST_OPTIONS: '{{default "" .TEST_OPTIONS}}'
      SOURCE_FILES: '{{default "./..." .SOURCE_FILES}}'
      TEST_PATTERN: '{{default "." .TEST_PATTERN}}'
    cmds:
      - go test {{.TEST_OPTIONS}} -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt {{.SOURCE_FILES}} -run {{.TEST_PATTERN}} -timeout=5m

  cover:
    desc: Open the cover tool
    cmds:
      - go tool cover -html=coverage.txt

  fmt:
    desc: gofumpt all code
    cmds:
      - gofumpt -w -l .

  lint:
    desc: Lint the code with golangci-lint
    cmds:
      - golangci-lint run --config ./.golangci.yaml ./...

  ci:
    desc: Run all CI steps
    cmds:
      - task: setup
      - task: build
      - task: test

  default:
    desc: Runs the default tasks
    cmds:
      - task: ci

  release:
    desc: Create a new tag
    vars:
      NEXT:
        sh: svu n
    cmds:
      - git tag {{.NEXT}}
      - echo {{.NEXT}}
      - git push origin --tags

  dottie:test:pkg:
    desc: Test a package
    cmds:
      - docker run --platform linux/{{ .Platform }} --rm --workdir /tmp -v $PWD/dist:/tmp {{ .Image }} sh -c '{{ .Cmd }} && goreleaser --version'

  dottie:test:rpm:
    desc: Tests rpm packages
    vars:
      rpm: "rpm --nodeps -ivh"
    cmds:
      - task: dottie:test:pkg
        vars:
          Platform: "386"
          Image: centos:centos7
          Cmd: "{{.rpm}} goreleaser-*.i386.rpm"
      - task: dottie:test:pkg
        vars:
          Platform: "amd64"
          Image: fedora
          Cmd: "{{.rpm}} goreleaser-*.x86_64.rpm"
      - task: dottie:test:pkg
        vars:
          Platform: "arm64"
          Image: fedora
          Cmd: "{{.rpm}} goreleaser-*.aarch64.rpm"

  dottie:test:deb:
    desc: Tests deb packages
    vars:
      dpkg: "dpkg --ignore-depends=git -i"
    cmds:
      - task: dottie:test:pkg
        vars:
          Platform: "amd64"
          Image: ubuntu
          Cmd: "{{.dpkg}} goreleaser*_amd64.deb"
      - task: dottie:test:pkg
        vars:
          Platform: "arm64"
          Image: ubuntu
          Cmd: "{{.dpkg}} goreleaser*_arm64.deb"
      - task: dottie:test:pkg
        vars:
          Platform: "arm/7"
          Image: ubuntu
          Cmd: "{{.dpkg}} goreleaser*_armhf.deb"

  dottie:test:apk:
    desc: Tests apk packages
    vars:
      apk: "apk add --allow-untrusted -U"
    cmds:
      - task: dottie:test:pkg
        vars:
          Platform: "386"
          Image: alpine
          Cmd: "{{.apk}} goreleaser*_x86.apk"
      - task: dottie:test:pkg
        vars:
          Platform: "amd64"
          Image: alpine
          Cmd: "{{.apk}} goreleaser*_x86_64.apk"
      - task: dottie:test:pkg
        vars:
          Platform: "arm64"
          Image: alpine
          Cmd: "{{.apk}} goreleaser*_aarch64.apk"
      - task: dottie:test:pkg
        vars:
          Platform: "arm/7"
          Image: alpine
          Cmd: "{{.apk}} goreleaser*_armv7.apk"

  dottie:test:
    desc: Test built linux packages
    cmds:
      - task: dottie:test:apk
      - task: dottie:test:deb
      - task: dottie:test:rpm

  goreleaser:
    desc: Run GoReleaser either in snapshot or release mode
    deps:
      - build
    vars:
      SNAPSHOT:
        sh: 'if [[ $GITHUB_REF != refs/tags/v* ]]; then echo "--snapshot"; fi'
    cmds:
      - goreleaser release --clean --timeout 60m {{ .SNAPSHOT }}

  nightly:
    cmds:
      - gh run list --workflow=nightly.yml
      - gh workflow run nightly.yml
      - sleep 30
      - gh run watch
