name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read # for actions/checkout to fetch code
  pull-requests: read # for golangci/golangci-lint-action to fetch pull requests

jobs:
  # ------------------------------

  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          args: --timeout=5m
          only-new-issues: true

  # ------------------------------
